[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # カーソル位置のコンテキストに合わせてftを切り替える
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]] # カーソル位置のコンテキストのftを判定するライブラリ
repo = 'Shougo/context_filetype.vim'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = {'colorscheme': 'wombat'}
'''

# [[plugins]] # 非同期でコードチェック
# repo = 'w0rp/ale'

[[plugins]]
repo = 'Townk/vim-autoclose'


[[plugins]]
repo = 'neoclide/coc.nvim'
build = './install.sh nightly'
hook_add='source ~/.config/nvim/coc-options.vim'

[[plugins]]
repo = 'raphamorim/lucario'


[[plugins]]# アイコン
repo = 'ryanoasis/vim-devicons'

# [ key ] ****************
[[plugins]] # csできるようにする
repo = 'tpope/vim-surround'

[[plugins]]# コメントアウトが簡単になる(gc)
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'rhysd/clever-f.vim'
# ************************ 

# [ snippets ] ***********
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neosnippet'
# ************************ 

# [ filer ] **************
[[plugins]]# ファイルみやすくなる
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
# ************************ 

# [ js ] *****************
[[plugins]]
repo = 'othree/yajs.vim'

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'

[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'

[[plugins]]
repo = 'othree/es.next.syntax.vim'
# ************************

# [ golang ] *************
[[plugins]]
repo = 'mattn/sonictemplate-vim'

[[plugins]]
repo = 'fatih/vim-go'
hook_add = '''
  let g:go_fmt_command = "goimports"
  let g:go_def_mapping_enabled = 0
  let g:go_doc_keywordprg_enabled = 0
'''

# ************************
