require 'plugins.plugins'
require 'plugins.fern'
-- require 'plugins.telescope'
require 'plugins.clap'
require 'plugins.treesitter'
require 'plugins.bufferline'
require 'plugins.ultisnips'
require 'plugins.gitsigns'
require 'plugins.galaxyline'
require 'plugins.gina'
require 'plugins.hlslens'
