[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
let g:ale_linters = { 
      \ 'cs': ['OmniSharp'],
      \ 'go': ['golint'],
      " \ 'typescriptreact': ['eslint'],
      " \ 'typescript': ['eslint'],
      " \ 'tsx': ['eslint'],
      " \ 'javascriptreact': ['eslint'],
      " \ 'javascript': ['eslint'],
      " \ 'jsx': ['eslint'],
      \ }
let g:ale_linters_explicit = 1
let g:ale_sign_error = '>>'
let g:ale_sign_warning = '⚠'
let g:ale_fix_on_save = 1
'''
# on_ft = ['cs','typescript','typescriptreact','tsx','javascript','javascriptreact','javascriptreact']
on_ft = ['cs','go']

[[plugins]]
repo = 'vim-test/vim-test'
hook_add = '''
let test#go#runner = 'gotest'
tmap <C-o> <C-\><C-n>

nmap <silent> t<C-n> :TestNearest<CR>
nmap <silent> t<C-f> :TestFile<CR>
nmap <silent> t<C-s> :TestSuite<CR>
nmap <silent> t<C-l> :TestLast<CR>
nmap <silent> t<C-g> :TestVisit<CR>
'''
on_ft = ['go']

# [ java ] ---------------
# ======================== 
[[plugins]]
repo = 'thinca/vim-quickrun'
on_ft = ['java']

# ======================== 
# ------------------------ 


# [ HTML&CSS ] -----------
# ======================== 
[[plugins]]
repo = 'cakebaker/scss-syntax.vim'
on_ft = ['html','css']

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css', 'javascript.jsx', 'typescript.tsx', 'typescript', 'javascript', 'vue']

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['html','css']

[[plugins]]
repo = 'tell-k/vim-browsereload-mac'
hook_add= ''' 
let g:returnApp = "iTerm"
nmap <Space>bc :ChromeReloadStart<CR>
nmap <Space>bC :ChromeReloadStop<CR>
nmap <Space>bf :FirefoxReloadStart<CR>
nmap <Space>bF :FirefoxReloadStop<CR>
nmap <Space>bs :SafariReloadStart<CR>
nmap <Space>bS :SafariReloadStop<CR>
nmap <Space>bo :OperaReloadStart<CR>
nmap <Space>bO :OperaReloadStop<CR>
nmap <Space>ba :AllBrowserReloadStart<CR>
nmap <Space>bA :AllBrowserReloadStop<CR>
'''
on_ft = ['html','css']

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
command! OpenBrowserCurrent execute "OpenBrowser" expand("%:p")
'''
on_ft = ['html','css']
# ========================
# ------------------------ 


# [ dart ] ---------------
# ========================
[[plugins]]
repo = 'dart-lang/dart-vim-plugin'
on_ft = ['dart']

[[plugins]]
repo = 'thosakwe/vim-flutter'
on_ft = ['dart']
# ========================
# ------------------------ 


# [ markdown ] -----------
# ======================== 
[[plugins]]
repo = 'previm/previm'
hook_add = '''
let g:previm_open_cmd = 'open -a Google\ Chrome'
'''
on_ft = ['markdown']
# ========================
# ------------------------ 


# [ mdx ] ----------------
# ======================== 
[[plugins]]
repo = 'jxnblk/vim-mdx-js'
on_ft = ['mdx']
# ========================
# ------------------------ 


# [ js ] -----------------
# ======================== 
[[plugins]]
repo = 'evanleck/vim-svelte'
on_ft = ['svelte']
# ======================== 
# ------------------------ 


# [ rust ] ---------------
# ========================
[[plugins]]
repo = 'rust-lang/rust.vim'
hook_add = '''
let g:rustfmt_autosave = 1
'''
on_ft = ['rust']
# ========================
# ------------------------


# [ rust ] ---------------
# ========================
[[plugins]]
repo = 'rhysd/vim-go-impl'
on_ft = ['go']
# ========================
# ------------------------

# [ ruby ] ---------------
# ========================
[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby']

[[plugins]]
repo = 'ruby-formatter/rufo-vim'
hook_add = '''
let g:rufo_auto_formatting = 1
'''

on_ft = ['ruby']
# ========================
# ------------------------

# [ clang ] --------------
# ========================
[[plugins]]
repo = 'rhysd/vim-clang-format'
hook_add = '''
autocmd FileType c ClangFormatAutoEnable
autocmd FileType cpp ClangFormatAutoEnable
autocmd FileType chh ClangFormatAutoEnable
let g:clang_format#style_options = {
            \ "AccessModifierOffset" : -4,
            \ "AllowShortIfStatementsOnASingleLine" : "true",
            \ "AlwaysBreakTemplateDeclarations" : "true",
            \ "Standard" : "C++20"}
'''

# ========================
# ------------------------

# ------------------------
# [ c# ] =================
[[plugins]]
repo = "OmniSharp/omnisharp-vim"
on_ft = ["cs"]
build = "xbuild server/OmniSharp.sln"
hook_add = '''
let g:OmniSharp_server_stdio = 1
let g:OmniSharp_highlighting = 0
autocmd FileType cs nnoremap gd :OmniSharpGotoDefinition<cr>
autocmd FileType cs nnoremap <C-m><c-n> :OmniSharpRename<cr>
autocmd FileType cs nnoremap <C-m><C-f> :OmniSharpCodeFormat<cr>
'''
# ========================
# ------------------------


# [ toml ] ---------------
# ========================
[[plugins]] 
repo = 'cespare/vim-toml'
on_ft = 'toml'
# ========================
# ------------------------
