[[plugins]]
repo = 'steelsojka/completion-buffers'
hook_add = '''
let g:completion_chain_complete_list = {
      \ 'default': [
      \    {'complete_items': ['lsp']},
      \    {'complete_items': ['buffers']},
      \  ]}
'''
