[[plugins]]
repo = 'SirVer/ultisnips'
hook_source = '''
  let g:UltiSnipsEditSplit="vertical"
  " let g:UltiSnipsJumpForwardTrigger="<C-n>"
  " let g:UltiSnipsJumpBackwardTrigger="<C-b>"
  " Nop is not work
  let g:UltiSnipsExpandTrigger="<C-/>"
'''
on_i = 1
