# [ go ] =================
# ======================== 
[[plugins]]
repo = 'fatih/vim-go'
hook_add = '''
let g:go_highlight_array_whitespace_error = 1
let g:go_highlight_chan_whitespace_error = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_space_tab_error = 1
let g:go_highlight_trailing_whitespace_error = 1
let g:go_highlight_operators = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_arguments = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_fields = 1
let g:go_highlight_types = 1
let g:go_highlight_build_constraints = 1
let g:go_highlight_generate_tags = 1
let g:go_highlight_variable_assignments = 1
let g:go_highlight_variable_declarations = 1
let g:go_code_completion_enabled = 0
let g:go_fmt_autosave = 0
let g:go_mod_fmt_autosave = 0
let g:go_gopls_enabled = 0
let g:go_def_mapping_enabled = 0
let g:go_template_autocreate = 0
'''

# ======================== 
# ======================== 

# [ HTML&CSS ] ===========
# ======================== 
[[plugins]]
repo = 'prettier/vim-prettier'
build = 'yarn install'
on_ft = ['javascript', 'typescript', 'css', 'less', 'scss', 'json', 'graphql', 'markdown', 'vue', 'yaml', 'html']

[[plugins]]
repo = 'cakebaker/scss-syntax.vim'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo = 'tell-k/vim-browsereload-mac'
hook_add= ''' 
let g:returnApp = "iTerm"
nmap <Space>bc :ChromeReloadStart<CR>
nmap <Space>bC :ChromeReloadStop<CR>
nmap <Space>bf :FirefoxReloadStart<CR>
nmap <Space>bF :FirefoxReloadStop<CR>
nmap <Space>bs :SafariReloadStart<CR>
nmap <Space>bS :SafariReloadStop<CR>
nmap <Space>bo :OperaReloadStart<CR>
nmap <Space>bO :OperaReloadStop<CR>
nmap <Space>ba :AllBrowserReloadStart<CR>
nmap <Space>bA :AllBrowserReloadStop<CR>
'''

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
command! OpenBrowserCurrent execute "OpenBrowser" expand("%:p")
'''
# ************************
# ************************ 


# [ dart ] ***************
# ************************ 
[[plugins]]
repo = 'dart-lang/dart-vim-plugin'
# ************************
# ************************ 


# [ markdown ] ************
# ************************ 
 [[plugins]]
 repo = 'previm/previm'
 hook_add = '''
 let g:previm_open_cmd = 'open -a Google\ Chrome'
 '''
# ************************
# ************************ 


# [ js ] *****************
# ************************ 
[[plugins]]
repo = 'posva/vim-vue'
hook_add = '''
let g:vue_pre_processors = 'detect_on_enter'
'''

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'

[[plugins]]
repo = 'mxw/vim-jsx'

[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'
hook_add = '''
let g:vim_jsx_pretty_colorful_config = 1
let g:vim_jsx_pretty_disable_tsx = 1
'''

[[plugins]]
repo = 'pangloss/vim-javascript'
hook_add = '''
set conceallevel=1
let g:javascript_plugin_jsdoc = 1
let g:javascript_plugin_flow = 1
'''
# ======================== 
# ======================== 

# [ rust ] ===============
# ========================
[[plugins]]
repo = 'rust-lang/rust.vim'
hook_add = '''
let g:rustfmt_autosave = 1
'''
# ========================
# ========================

# [ ruby ] ===============
# ========================
[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'ruby-formatter/rufo-vim'
hook_add = '''
let g:rufo_auto_formatting = 1
'''
# ========================
# ========================

