[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
let g:ale_linters = { 
      \ 'cs': ['OmniSharp'],
      " \ 'typescriptreact': ['eslint'],
      " \ 'typescript': ['eslint'],
      " \ 'tsx': ['eslint'],
      " \ 'javascriptreact': ['eslint'],
      " \ 'javascript': ['eslint'],
      " \ 'jsx': ['eslint'],
      \ }
let g:ale_linters_explicit = 1
let g:ale_sign_error = '>>'
let g:ale_sign_warning = '--'
let g:ale_fix_on_save = 1
'''
# on_ft = ['cs','typescript','typescriptreact','tsx','javascript','javascriptreact','javascriptreact']
on_ft = ['cs']


# [ go ] -----------------
# ======================== 
[[plugins]]
repo = 'fatih/vim-go'
hook_add = '''
let g:go_highlight_array_whitespace_error = 1
let g:go_highlight_chan_whitespace_error = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_space_tab_error = 1
let g:go_highlight_trailing_whitespace_error = 1
let g:go_highlight_operators = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_arguments = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_fields = 1
let g:go_highlight_types = 1
let g:go_highlight_build_constraints = 1
let g:go_highlight_generate_tags = 1
let g:go_highlight_variable_assignments = 1
let g:go_highlight_variable_declarations = 1
let g:go_code_completion_enabled = 0
let g:go_fmt_autosave = 0
let g:go_mod_fmt_autosave = 0
let g:go_gopls_enabled = 0
let g:go_def_mapping_enabled = 0
let g:go_template_autocreate = 0
'''
on_ft = ['go']

# ======================== 
# ------------------------ 


# [ java ] ---------------
# ======================== 
[[plugins]]
repo = 'thinca/vim-quickrun'
on_ft = ['java']

# ======================== 
# ------------------------ 


# [ HTML&CSS ] -----------
# ======================== 
[[plugins]]
repo = 'cakebaker/scss-syntax.vim'
on_ft = ['html','css']

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html','css','jsx','tsx','javascriptreact','typescriptreact','vue']

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['html','css']

[[plugins]]
repo = 'tell-k/vim-browsereload-mac'
hook_add= ''' 
let g:returnApp = "iTerm"
nmap <Space>bc :ChromeReloadStart<CR>
nmap <Space>bC :ChromeReloadStop<CR>
nmap <Space>bf :FirefoxReloadStart<CR>
nmap <Space>bF :FirefoxReloadStop<CR>
nmap <Space>bs :SafariReloadStart<CR>
nmap <Space>bS :SafariReloadStop<CR>
nmap <Space>bo :OperaReloadStart<CR>
nmap <Space>bO :OperaReloadStop<CR>
nmap <Space>ba :AllBrowserReloadStart<CR>
nmap <Space>bA :AllBrowserReloadStop<CR>
'''
on_ft = ['html','css']

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
command! OpenBrowserCurrent execute "OpenBrowser" expand("%:p")
'''
on_ft = ['html','css']
# ========================
# ------------------------ 


# [ dart ] ---------------
# ========================
[[plugins]]
repo = 'dart-lang/dart-vim-plugin'
on_ft = ['dart']

[[plugins]]
repo = 'thosakwe/vim-flutter'
on_ft = ['dart']
# ========================
# ------------------------ 


# [ markdown ] -----------
# ======================== 
[[plugins]]
repo = 'previm/previm'
hook_add = '''
let g:previm_open_cmd = 'open -a Google\ Chrome'
'''
on_ft = ['markdown']
# ========================
# ------------------------ 


# [ js ] -----------------
# ======================== 
[[plugins]]
repo = 'posva/vim-vue'
hook_add = '''
let g:vue_pre_processors = 'detect_on_enter'
'''
on_ft = ['vue']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript','tsx','typescriptreact']

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript','typescript','jsx', 'tsx', 'javascriptreact', 'typescriptreact']

[[plugins]]
repo = 'othree/es.next.syntax.vim'
on_ft = ['javascript','typescript','jsx', 'tsx', 'javascriptreact', 'typescriptreact']

[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'
hook_add = '''
let g:vim_jsx_pretty_colorful_config = 1
" let g:vim_jsx_pretty_disable_tsx = 1
'''
on_ft = ['javascript','typescript','jsx', 'tsx', 'javascriptreact', 'typescriptreact']

[[plugins]]
repo = 'pangloss/vim-javascript'
hook_add = '''
set conceallevel=1
let g:javascript_plugin_jsdoc = 1
let g:javascript_plugin_flow = 1
'''
on_ft = ['javascript','typescript','jsx', 'tsx', 'javascriptreact', 'typescriptreact']
# ======================== 
# ------------------------ 


# [ rust ] ---------------
# ========================
[[plugins]]
repo = 'rust-lang/rust.vim'
hook_add = '''
let g:rustfmt_autosave = 1
'''
on_ft = ['rust']
# ========================
# ------------------------


# [ ruby ] ---------------
# ========================
[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby']

[[plugins]]
repo = 'ruby-formatter/rufo-vim'
hook_add = '''
let g:rufo_auto_formatting = 1
'''

on_ft = ['ruby']
# ========================
# ------------------------

# [ clang ] --------------
# ========================
[[plugins]]
repo = 'rhysd/vim-clang-format'
hook_add = '''
autocmd FileType c ClangFormatAutoEnable
autocmd FileType cpp ClangFormatAutoEnable
autocmd FileType chh ClangFormatAutoEnable
let g:clang_format#style_options = {
            \ "AccessModifierOffset" : -4,
            \ "AllowShortIfStatementsOnASingleLine" : "true",
            \ "AlwaysBreakTemplateDeclarations" : "true",
            \ "Standard" : "C++20"}
'''

# ========================
# ------------------------

# ------------------------
# [ c# ] =================
[[plugins]]
repo = "OmniSharp/omnisharp-vim"
on_ft = ["cs"]
build = "xbuild server/OmniSharp.sln"
hook_add = '''
let g:OmniSharp_server_stdio = 1
let g:OmniSharp_highlighting = 0
autocmd FileType cs nnoremap gd :OmniSharpGotoDefinition<cr>
autocmd FileType cs nnoremap <C-m><c-n> :OmniSharpRename<cr>
autocmd FileType cs nnoremap <C-m><C-f> :OmniSharpCodeFormat<cr>
'''
# ========================
# ------------------------


# [ toml ] ---------------
# ========================
[[plugins]] 
repo = 'cespare/vim-toml'
on_ft = 'toml'
# ========================
# ------------------------
