[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
let g:fern#renderer = "nerdfont"
noremap <silent> <Space>f :Fern . -reveal=% <CR>

function! s:init_fern() abort
  nmap <buffer> <CR> <Plug>(fern-my-open-expand-collapse)
  nmap <buffer><nowait> H <Plug>(fern-action-leave)
  nmap <buffer><nowait> L <Plug>(fern-action-enter)
  nmap <buffer> # <Plug>(fern-action-project-top:reveal)
endfunction

augroup fern-custom
  autocmd! *
  autocmd FileType fern call s:init_fern()
augroup END
'''

[[plugins]]
repo = 'lambdalisue/fern-hijack.vim'
depends = ['fern.vim']

[[plugins]]
repo = 'lambdalisue/fern-mapping-project-top.vim'
depends = ['fern.vim']

[[plugins]]
repo = 'hrsh7th/fern-mapping-collapse-or-leave.vim'
depends = ['fern.vim']

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
depends = ['fern.vim']

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'
depends = ['fern.vim']

[[plugins]]
repo = 'lambdalisue/glyph-palette.vim'
hook_add = '''
augroup my-glyph-palette
  autocmd! *
  autocmd FileType fern call glyph_palette#apply()
  autocmd FileType nerdtree,startify call glyph_palette#apply()
augroup END
'''
depends = ['fern.vim']

