[[plugins]]
repo = 'Shougo/dein.vim'

# colorscheme
[[plugins]]
repo = 'sainnhe/gruvbox-material'

# neovim #12587
[[plugins]]
repo = 'antoinemadec/FixCursorHold.nvim'
hook_add = '''
let g:cursorhold_updatetime = 100
'''

# fzf
[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
marge = 0

[[plugins]]
repo = 'machakann/vim-sandwich'

# [ lightline ] ------------------------
# ======================================
[[plugins]]
repo = 'itchyny/lightline.vim'

hook_add = '''
let g:lightline = {
      \ 'colorscheme': 'gruvbox_material',
      \ 'component_function': {
      \   'filename': 'LightlineFilename',
      \ },
      \ 'enable': {'tabline': 0},
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ], [ 'readonly', 'filename', 'modified' ] ]
      \ },
      \ 'separator': { 'left': '', 'right': '' },
      \ 'subseparator': { 'left': '', 'right': '' },
      \ }


function! LightlineFilename()
  let root = fnamemodify(get(b:, 'git_dir'), ':h')
  let path = expand('%:p')
  if path[:len(root)-1] ==# root
    return path[len(root)+1:]
  endif
  return expand('%')
endfunction

autocmd BufWritePost,TextChanged,TextChangedI * call lightline#update()
set showtabline=2
'''
# ======================================
# --------------------------------------

# [ filetype ] -------------------------
# ======================================
[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim'] 
hook_add = '''
let g:context_filetype#search_offset = 100
	let g:precious_enable_switchers = {
	\	"vue" : {
	\		"setfiletype" : 0
	\	},
	\}
'''

[[plugins]]
repo = 'Shougo/context_filetype.vim'
# ======================================
# --------------------------------------


# [ git ] ------------------------------
# ======================================
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = "airblade/vim-gitgutter"
hook_add = '''
nnoremap <silent> ,gh :<C-u>GitGutterLineHighlightsToggle<CR>
'''

[[plugins]]
repo = 'lambdalisue/gina.vim'
hook_add = '''
nnoremap <silent><space>gs :<C-u>Gina status --opener="botright split"<CR>
nnoremap <silent><space>ct :<C-u>Gina commit<CR>
call gina#custom#command#alias('status', 'st')
call gina#custom#command#alias('commit', 'ct')
'''

# ======================================
# --------------------------------------


# [ highlight ] ------------------------
# ======================================
[[plugins]]
repo = 'itchyny/vim-parenmatch'

[[plugins]]
repo = 'chrisbra/Colorizer'

[[plugins]]
repo = 'thinca/vim-zenspace'
hook_add = '''
let g:zenspace#default_mode = 'on'
'''

[[plugins]]
repo = 'machakann/vim-highlightedyank'
hook_add = '''
let g:highlightedyank_highlight_duration = 200
'''
# ======================================
# --------------------------------------


# [ keymap ] ---------------------------
# ======================================
[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-operator-replace'
hook_add = '''
map <Space>s <Plug>(operator-replace)
'''

[[plugins]]
repo = 'christoomey/vim-tmux-navigator'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'rhysd/clever-f.vim'

[[plugins]]
repo = 'liuchengxu/vim-clap'
hook_add = '''
let g:clap_enable_icon = 1
let g:clap_insert_mode_only = v:true
nnoremap <silent><Space>cf 
\ :<C-u>Clap files<CR>
nnoremap <silent><Space>cg 
\ :<C-u>Clap grep<CR>
nnoremap <silent><Space>cb 
\ :<C-u>Clap buffers<CR>
nnoremap <silent><Space>cy 
\ :<C-u>Clap yanks<CR>
'''

[[plugins]]
repo = 'zefei/vim-wintabs'
hook_add = '''
nmap <C-t><C-l> <plug>(wintabs_next)
nmap <C-t><C-h> <plug>(wintabs_previous)
nmap <C-t><C-p> <plug>(wintabs_close)
'''

[[plugins]]
repo = 'zefei/vim-wintabs-powerline'

[[plugins]]
repo = 'tyru/columnskip.vim'
hook_add = '''
nmap sj <Plug>(columnskip:nonblank:next)
omap sj <Plug>(columnskip:nonblank:next)
xmap sj <Plug>(columnskip:nonblank:next)
nmap sk <Plug>(columnskip:nonblank:prev)
omap sk <Plug>(columnskip:nonblank:prev)
xmap sk <Plug>(columnskip:nonblank:prev)
'''
# ======================================
# --------------------------------------
